# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.1
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Fabric API
fabric_version=0.134.1+1.21.10

# Mod Properties
mod_version = 1.0.19
maven_group = com.adryd
archives_base_name = sneaky
